# DATABASE SERVER

- hosts: db_server
  become: true
  vars_files: vars/main.yml
  vars:
    root_password: "my_secret_password"

  tasks:
#  - name: install mysql
#    dnf:
#      name:
#        - mariadb-server
       # - python3-PyMySQL # for mysql_db and mysql_user modules
#      state: present
#      update_cache: yes

  - name: Allow external MySQL connexions (1/2)
    lineinfile:
      path: /etc/my.cnf.d/mariadb-server.cnf
      regexp: '^skip-external-locking'
      line: "# skip-external-locking"
    notify: Restart Restart MariaDB

  - name: Allow external MySQL connexions (2/2)
    lineinfile:
      path: /etc/my.cnf.d/mariadb-server.cnf
      regexp: '^bind-address'
      line: "# bind-address"
    notify: Restart MariaDB

  - name: upload sql table config
    template:
      src: "table.sql.j2"
      dest: "/tmp/table.sql"

  - name: add sql table to database
    mysql_db:
      name: "{{ mysql_dbname }}"
      state: present
      login_user: root
      login_password: '{{ root_password }}'
      state: import
      target: /tmp/table.sql

  - name: "Create {{ mysql_user }} with all {{ mysql_dbname }} privileges"
    mysql_user:
      name: "{{ mysql_user }}"
      password: "{{ mysql_password }}"
      priv: "{{ mysql_dbname }}.*:ALL"
      host: "{{ webserver_host }}"
      state: present
      login_user: root
      login_password: '{{ root_password }}'
      login_unix_socket: /var/lib/mysql/mysql.sock

  handlers:
    - name: Restart MariaDB
      service:
        name: mariadb
        state: restarted
