- hosts: all
  become: yes
  become_method: sudo
  vars_prompt:
    - name: "ansible_become_pass"
      prompt: "Enter sudo password"
      private: yes
  tasks:
    - name: General packages are installed
      apt:
        name: '{{packages}}'
        state: present
      vars:
        packages:
        - tar
        - wget
        - unzip
      tags: General_Packages
      when: ansible_facts['os_family'] == "Debian"

    - name: Install packages on RedHat-based systems
      yum:
        name: '{{ packages }}'
        state: present
      vars:
        packages:
          - tar
          - wget
          - unzip
      tags: General_Packages
      when: ansible_facts['os_family'] == "RedHat"
