---
# tasks file for FortiGate

- name: Configure global attributes on FortiGate
  fortinet.fortios.fortios_system_global:
    vdom: "{{ vdom }}"
    system_global:
      hostname: "{{ global_config.hostname }}"
      admin_concurrent: 'enable'
      timezone: "{{ global_config.timezone }}"
      admintimeout: 120
      gui_date_format: "{{ global_config.date_format }}"
      language: "{{ global_config.language }}"
      alias: 'FortiGate'
      admin_ssh_port: 22
      admin_https_redirect: "enable"
      admin_lockout_duration: 30
      admin_lockout_threshold: 3

- name: Configure FortiGate VLANs on LAN interface
  fortinet.fortios.fortios_system_interface:
    vdom: '{{ vdom }}'
    state: present
    system_interface:
      name: VLAN.'{{ item.id }}'
      vlan_id: "{{ item.id }}"
      type: 'vlan'
      interface: "{{ interface_lan.name }}"
      ip: "{{ item.ip }}"
      allowaccess: '{{ item.allowaccess }}'
  loop: "{{ vlan_configs }}"

- name: Configure FortiGate DHCP
  fortinet.fortios.fortios_system_dhcp_server:
    vdom: '{{ vdom }}'
    state: present
    system_dhcp_server:
      interface: VLAN."{{ item.vlan }}"
      auto_configuration: 'disable'
      auto_managed_status: 'disable'
      status: 'enable'
      timezone: '01'
      dns_server2: '{{ dns_server2 }}'
      dns_server3: '{{ dns_server3 }}'
      dns_service: 'local'
      domain: '{{ domain }}'
      netmask: "{{ item.netmask }}"
      default_gateway: "{{ item.gateway }}"
      ip_mode: 'range'
      ip_range:
        start_ip: "{{ item.start_ip }}"
        end_ip: "{{ item.end_ip }}"
        id: '{{ item.vlan }}'
      lease_time: '604800'
    loop: "{{ dhcp_configs }}"

- name: Configure FortiGate WAN interface
  fortinet.fortios.fortios_system_interface:
    vdom: '{{ vdom }}'
    state: present
    system_interface:
      name: "{{ item.name}}"
      alias: '{{ item.alias }}'
      ip: '{{ item.wan_ip }}'
      allowaccess: '{{ item.allowaccess }}'
    loop: '{{ interface_wan }}'

- name: Configure FortiGate LAN interface
  fortinet.fortios.fortios_system_interface:
    vdom: '{{ vdom }}'
    state: present
    system_interface:
      name: '{{ interface_lan.name }}'
      alias: '{{ interfac_lan.alias }}'

- name: Configure FortiGate static route
  fortinet.fortios.fortios_router_static:
    vdom: '{{ vdom }}'
    state: present
    router_static:
      - dst: "{{ item.destination }}"
        gateway: "{{ item.gateway }}"
        device: "{{ item.interface }}"
        comment: '{{ item.comment }}'
        status: 'enable'
    loop: "{{ static_routes }}"
